### ISSUE TITLE
Problems with collins 1.3.0 collins.sh script

### ISSUE THREAD

**Issue by kgoedert** [tumblr/collins#250]
Hi

When I execute  sudo -u ubuntu /home/ubuntu/collins/scripts/collins.sh initdb username passwd I get the following error:

Initializing collins database on localhost...
Please enter mysql root password. Press <enter> for none.
Enter password: 
Granting privs to collins user on localhost...
Please enter mysql root password. Press <enter> for none.
Enter password: 
Running migrationsError: Could not find or load main class DbUtil
 * 

I am using a ubuntu 14.04 installed on a VirtualBox. 

Thanks for any help

**Comment by byxorna** [comment]
Hey @kgoedert . We have seen people have issues with this before on debian based systems. Usually this has stemmed from an incorrect classpath. Whats your ```$JAVA_HOME``` look like? Also, is ```collins.sh start``` able to find play.core.server.NettyServer?
https://github.com/tumblr/collins/blob/0c78c643b6f58e4a85a02b6199257b63bb5a5bcc/scripts/collins.sh#L103

 cc @maddalab

**Comment by byxorna** [comment]
Possibly related: https://github.com/tumblr/collins/issues/217 https://github.com/tumblr/collins/issues/173 https://github.com/tumblr/collins/issues/149
Also, just to humor me, can you try with the latest collins.sh in master? Thanks!

**Comment by kgoedert** [comment]
my JAVA_HOME is set to /usr/bin/java

If I run sh collins/scripts/collins.sh start I get collins/scripts/collins.sh: 43: collins/scripts/collins.sh: Syntax error: "(" unexpected

**Comment by kgoedert** [comment]
Tried the version of collins.sh on master, and got the same results

**Comment by byxorna** [comment]
@kgoedert thats interesting. Is ubuntu not using bash? or is bash a symlink to another shell? https://github.com/tumblr/collins/blob/v1.3.0/scripts/collins.sh#L43 @roymarantz suspects that we are using a newer function syntax that should instead be ```function running {...}```

Typically the DbUtil class not found errors are because the APP_HOME is incorrect, so the classpath is not set appropriately (see https://github.com/tumblr/collins/blob/v1.3.0/scripts/collins.sh#L14 and https://github.com/tumblr/collins/blob/v1.3.0/scripts/collins.sh#L133 ). Have you overridden variables like APP_HOME to the root of your app's installation directory with /etc/sysconfig/collins? https://github.com/tumblr/collins/blob/v1.3.0/scripts/collins.sh#L35 sets the default which i suspect is not where your app is installed...

**Comment by kgoedert** [comment]
Hi,

my APP_HOME was wrong, I echoed it and it had no value, but the file in  /etc/sysconfig/collins was correct. I set the APP_HOME home manually on the script and now I get:

Running evolutions...
Exception in thread "main" java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:274)
	at scala.None$.get(Option.scala:272)
	at play.api.db.evolutions.OfflineEvolutions$.applyScript(Evolutions.scala:513)
	at DbUtil$delayedInit$body.apply(DbUtil.scala:10)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:60)
	at scala.App$$anonfun$main$1.apply(App.scala:60)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:45)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:30)
	at scala.App$class.main(App.scala:60)
	at DbUtil$.main(DbUtil.scala:4)
	at DbUtil.main(DbUtil.scala)
 *

**Comment by byxorna** [comment]
@kgoedert that is a very interesting error; I have never seen this before. Sounds like your classpath is still screwed up, because it appears the DbUtil is unable to get the class loader. Can you add -x to the shebang line of collins.sh so we can see exactly what is happening?

**Comment by windowsrefund** [comment]
Seeing this on a freshly installed 1.3.0 ontop of CentOS 6.4

Could not find the main class: collins.DbUtil.  Program will exit

Worth noting perhaps is that I followed the install steps from http://tumblr.github.io/collins/recipes.html#centos

I'd be willing to go to CentOS 6.5 though if that's what's needed.
