### ISSUE TITLE
collins-shell 0.2.21 seems to be broken: 'cannot load such file' error

### ISSUE THREAD

**Issue by brad-babb** [tumblr/collins#287]
I've recently installed the collins-shell, and when I attempt to run the command it fails with the following error:

```
bundle exec collins-shell
/home/vagrant/.anyenv/envs/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/pry-0.9.9.6/lib/pry.rb:171:in `require': cannot load such file -- readline (LoadError)
	from /home/vagrant/.anyenv/envs/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/pry-0.9.9.6/lib/pry.rb:171:in `<top (required)>'
	from /home/vagrant/.anyenv/envs/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/collins_shell-0.2.21/lib/collins_shell/console.rb:2:in `require'
	from /home/vagrant/.anyenv/envs/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/collins_shell-0.2.21/lib/collins_shell/console.rb:2:in `<top (required)>'
	from /home/vagrant/.anyenv/envs/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/collins_shell-0.2.21/lib/collins_shell/cli.rb:3:in `require'
	from /home/vagrant/.anyenv/envs/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/collins_shell-0.2.21/lib/collins_shell/cli.rb:3:in `<top (required)>'
	from /home/vagrant/.anyenv/envs/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/collins_shell-0.2.21/bin/collins-shell:15:in `require'
	from /home/vagrant/.anyenv/envs/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/collins_shell-0.2.21/bin/collins-shell:15:in `block in <top (required)>'
	from /home/vagrant/.anyenv/envs/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/collins_shell-0.2.21/bin/collins-shell:15:in `each'
	from /home/vagrant/.anyenv/envs/rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/collins_shell-0.2.21/bin/collins-shell:15:in `<top (required)>'
	from /home/vagrant/.anyenv/envs/rbenv/versions/1.9.3-p547/bin/collins-shell:23:in `load'
	from /home/vagrant/.anyenv/envs/rbenv/versions/1.9.3-p547/bin/collins-shell:23:in `<main>'
```

using rbenv (with ruby 1.9.3-p551) under anyenv, and installed the shell using:

```
bundle install
```

with ```Gemfile```

```
source 'https://rubygems.org'

gem 'collins_shell', '0.2.21'
```

which installed the following versions:

```
GEM
  remote: https://rubygems.org/
  specs:
    coderay (1.0.9)
    collins_client (0.2.15)
      httparty (~> 0.8.3)
    collins_shell (0.2.21)
      collins_client (~> 0.2.11)
      highline (~> 1.6.15)
      mustache (~> 0.99.4)
      pry (~> 0.9.9.6)
      rubygems-update (~> 1.8.24)
      terminal-table (~> 1.4.5)
      thor (~> 0.16.0)
    highline (1.6.21)
    httparty (0.8.3)
      multi_json (~> 1.0)
      multi_xml
    method_source (0.7.1)
    multi_json (1.11.0)
    multi_xml (0.5.5)
    mustache (0.99.8)
    pry (0.9.9.6)
      coderay (~> 1.0.5)
      method_source (~> 0.7.1)
      slop (>= 2.4.4, < 3)
    rubygems-update (1.8.30)
    slop (2.4.4)
    terminal-table (1.4.5)
    thor (0.16.0)

PLATFORMS
  ruby

DEPENDENCIES
  collins_shell (= 0.2.21)
```

I've tried this using:
- Ubuntu 14.04
- Centos 6.06

It fails the same way on both OSes.

**Comment by brad-babb** [comment]
It seems to work on OSX under anyenv/rbenv, ruby version ruby 1.9.3p547.

**Comment by byxorna** [comment]
@brad-babb interesting. I was going to say that pry isnt specifying all their dependencies in their gemfile, but I believe readline should be bundled into the ruby interpreter itsself. Is it possible that your RVM ruby was not compiled with readline support?

**Comment by byxorna** [comment]
Alternatively, https://github.com/byxorna/collins-cli may provide a nicer experience. (/shameless plug, PRs welcome)

**Comment by brad-babb** [comment]
@byxorna I'll double check the readline support.  The compilation didn't have any errors as far as I can tell.  I'll so I'm using [rbenv](https://github.com/sstephenson/rbenv) and not RVM.  I don't know if that makes a difference.

Thanks for the collins-cli suggestion, I'll give it a try as well.

**Comment by brad-babb** [comment]
So it looks like missing readline development package was the cause.  Fixed it by running:

(on Ubuntu 14.04)

```
sudo apt-get install libreadline6-dev
```

(on Centos 6.6)

```
sudo yum install -y readline-devel
```

Then using rbenv to uninstall/reinstall ruby, then re-installing the collins-shell.

Thanks @byxorna !

On another note: Can your collins-cli application be installed via a gem? Or is it available only as source at this point?

**Comment by byxorna** [comment]
Great, thanks @brad-babb! Yes, you can install collins-cli as a gem: https://rubygems.org/gems/collins-cli
```
-> $ gem search collins-cli

*** REMOTE GEMS ***

collins-cli (0.2.3)
```

Feel free to open any PRs on it or feature enhancements.
