### ISSUE TITLE
IP Allocation in default pool fails

### ISSUE THREAD

**Issue by byxorna** [tumblr/collins#416]
Attempting to allocate IP addresses out of the default pool fails. It seems the pool name isnt properly handled by the API :(
## production.conf

```
  ipAddresses {
    pools {
...
      DEFAULT {
        network="192.168.5.0/24"
        startAddress="192.168.5.2"
      }
...  
  }
```

Correct behavior when specifying a missing pool:

```
2.3.0 :028 > c.ipaddress_allocate!('123', 'FUCK')
Collins::RequestError: Error processing request: Pool FUCK does not exist. Valid pools are: ADMIN-OPS, WEB-EDIT, DEFAULT, DEV, WEB-SECURE
```

When specifying a working pool, it works:

```
2.3.0 :030 > c.ipaddress_allocate!('123', 'DEV')
 => [#<Collins::Address:0x007fe0331549e0 @id=1, @asset_id=2, @address="172.16.5.4", @gateway="172.16.5.1", @netmask="255.255.255.0", @pool="DEV">]
```

However, when allocating from the default pool, it fails: (same behavior with `'DEFAULT'`, `""`, `nil`)

```
2.3.0 :031 > c.ipaddress_allocate!('123', 'DEFAULT')
Collins::RichRequestError: Error processing request
        from /Users/gabe/.rvm/gems/ruby-2.3.0/gems/collins_client-0.2.18/lib/collins/api/util/errors.rb:8:in `handle_error'
        from /Users/gabe/.rvm/gems/ruby-2.3.0/gems/collins_client-0.2.18/lib/collins/api/util/responses.rb:12:in `parse_response'
        from /Users/gabe/.rvm/gems/ruby-2.3.0/gems/collins_client-0.2.18/lib/collins/api/ip_address.rb:14:in `block in ipaddress_allocate!'
        from /Users/gabe/.rvm/gems/ruby-2.3.0/gems/collins_client-0.2.18/lib/collins/api/util/requests.rb:31:in `block in http_put'
        from /Users/gabe/.rvm/gems/ruby-2.3.0/gems/collins_client-0.2.18/lib/collins/api/util/requests.rb:83:in `block in http_call'
        from /Users/gabe/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
        from /Users/gabe/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
        from /Users/gabe/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:33:in `catch'
        from /Users/gabe/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:33:in `catch'
        from /Users/gabe/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
        from /Users/gabe/.rvm/gems/ruby-2.3.0/gems/collins_client-0.2.18/lib/collins/api/util/requests.rb:82:in `http_call'
        from /Users/gabe/.rvm/gems/ruby-2.3.0/gems/collins_client-0.2.18/lib/collins/api/util/requests.rb:27:in `http_put'
        from /Users/gabe/.rvm/gems/ruby-2.3.0/gems/collins_client-0.2.18/lib/collins/api/ip_address.rb:13:in `ipaddress_allocate!'
        from (irb):31
        from /Users/gabe/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'

2.3.0 :041 > c.ipaddress_pools.map{|x| x['NAME']}
 => ["ADMIN-OPS", "WEB-EDIT", "", "DEV", "WEB-SECURE"]
```

You can see the failures in the logs:

```
2016-02-19 19:53:23,262 - [DEBUG] - application - c.c.SecureApiController$class:authenticate:160 - Logged in user blake
2016-02-19 19:53:23,263 - [DEBUG] - application - c.c.a.SecureAction:checkAuthorization:124 - Auth required for /api/asset/123/address and requested by blake was successful
2016-02-19 19:53:23,266 - [DEBUG] - application - c.c.a.SecureAction:checkAuthorization:129 - Credentials required and found for resource /api/asset/123/address, user blake
2016-02-19 19:53:23,273 - [INFO] - application - c.m.s.IpAddressStorage$class:createWithRetry:107 - createAddressWithRetry attempt 1: no collins.models.IpAddresses$ configuration found
2016-02-19 19:53:23,274 - [INFO] - application - c.m.s.IpAddressStorage$class:createWithRetry:107 - createAddressWithRetry attempt 2: no collins.models.IpAddresses$ configuration found
2016-02-19 19:53:23,274 - [INFO] - application - c.m.s.IpAddressStorage$class:createWithRetry:107 - createAddressWithRetry attempt 3: no collins.models.IpAddresses$ configuration found
2016-02-19 19:53:23,275 - [INFO] - application - c.m.s.IpAddressStorage$class:createWithRetry:107 - createAddressWithRetry attempt 4: no collins.models.IpAddresses$ configuration found
2016-02-19 19:53:23,276 - [INFO] - application - c.m.s.IpAddressStorage$class:createWithRetry:107 - createAddressWithRetry attempt 5: no collins.models.IpAddresses$ configuration found
2016-02-19 19:53:23,277 - [INFO] - application - c.m.s.IpAddressStorage$class:createWithRetry:107 - createAddressWithRetry attempt 6: no collins.models.IpAddresses$ configuration found
2016-02-19 19:53:23,277 - [INFO] - application - c.m.s.IpAddressStorage$class:createWithRetry:107 - createAddressWithRetry attempt 7: no collins.models.IpAddresses$ configuration found
2016-02-19 19:53:23,278 - [INFO] - application - c.m.s.IpAddressStorage$class:createWithRetry:107 - createAddressWithRetry attempt 8: no collins.models.IpAddresses$ configuration found
2016-02-19 19:53:23,278 - [INFO] - application - c.m.s.IpAddressStorage$class:createWithRetry:107 - createAddressWithRetry attempt 9: no collins.models.IpAddresses$ configuration found
2016-02-19 19:53:23,279 - [INFO] - application - c.m.s.IpAddressStorage$class:createWithRetry:107 - createAddressWithRetry attempt 10: no collins.models.IpAddresses$ configuration found
```

@Primer42 @defect @schallert @roymarantz

**Comment by maddalab** [comment]
Either your invocation or the the gem is the issue, pool name is optional in scala and in the api. When not specified it takes the default pool.

I recommend @gtorre fix it. What do you think @lqmccoy?

**Comment by komapa** [comment]
Bhaskar with the bag of jokes :)
