### ISSUE TITLE
setup script not creating mysql tables

### ISSUE THREAD

**Issue by betterltn** [tumblr/collins#444]
collins fails to start with error 

	... 52 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'collins.asset_meta' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)

mysql credencials are fine .

**Comment by byxorna** [comment]
Collins will not run evolutions by default, so you need to create your schema before starting collins up manually (or remember the magic play incantation to try to apply evolutions on startup).

Try something like this in your config, and see if it applies evolutions.
```# mysql DB config
evolutionplugin=enabled
applyEvolutions.collins=true
applyDownEvolutions.collins=true```

**Comment by replicant0wnz** [comment]
Where can I find a copy of the schema?

**Comment by replicant0wnz** [comment]
FYI,

The above does not exist in the default Docker config .. Took some searching to find this thread.

**Comment by Primer42** [comment]
@replicant0wnz it looks like at least the forward direction is present in the docker config:
https://github.com/tumblr/collins/blob/master/conf/docker/database.conf#L2
https://github.com/tumblr/collins/blob/master/conf/docker/database.conf#L12
And since docker is using the in-memory database, you shouldn't ever be in a situation where you would need to downgrade your schema.

Can you give me some steps to reproduce the error you ran into?

**Comment by replicant0wnz** [comment]
Er, sorry. It's not in the following file:

https://github.com/tumblr/collins/blob/master/conf/docker/database.conf.mysql

If you wanted to persist the data and use MySQL I assumed you simply copy that file to database.conf and add your server settings. Unless you add the above evolution items it won't create the schema.

**Comment by Primer42** [comment]
@replicant0wnz yep - that was an intentional choice.  That's because, in general, we find that when people run with mysql, they don't want evolutions to happen automatically.  Plus, that file isn't going to work out of the box for anyone since you'll have to modify the `db.collins.url` to point at your database.

**Comment by replicant0wnz** [comment]
Gotcha. So I did modify the file w/the my correct DB config but it would not create the schema unless I turned on evolutions (my original issue). I also didn't see anywhere in the documentation on how to create the schema.

**Comment by byxorna** [comment]
@replicant0wnz if you use the `database.conf.mysql` with the fields set like so:
```
evolutionplugin=enabled
applyEvolutions.collins=true
applyDownEvolutions.collins=true
```
the evolutions will create your schema.

**Comment by replicant0wnz** [comment]
@byxorna that's exactly what I did, but due to lack of documentation I had to find out that information from this thread per your earlier reply ;-)
