### ISSUE TITLE
collins crashes when accessing asset without ipmi data

### ISSUE THREAD

**Issue by discordianfish** [tumblr/collins#454]
Hi,

I've created a new asset with generate_ipmi=false and uploaded lldp and lshw data. All that worked but when accessing the asset via the UI (probably API as well) collins throws an "Oops, an error occured" with this in the log:

```
2016-08-16 15:41:00.118462500  [error] application - 
2016-08-16 15:41:00.118479500  
2016-08-16 15:41:00.118482500  ! @714phimm1 - Internal server error, for (GET) [/resource/76] ->
2016-08-16 15:41:00.118484500  
2016-08-16 15:41:00.118486500  play.api.Application$$anon$1: Execution exception[[IllegalStateException: No IPMI configuration for asset MY_ASSET]]
2016-08-16 15:41:00.118489500  	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
2016-08-16 15:41:00.118491500  	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
2016-08-16 15:41:00.118493500  	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
2016-08-16 15:41:00.118497500  	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
2016-08-16 15:41:00.118499500  	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.7.jar:na]
2016-08-16 15:41:00.118501500  Caused by: java.lang.IllegalStateException: No IPMI configuration for asset MY_ASSET
2016-08-16 15:41:00.118503500  	at collins.power.management.IpmiPowerCommand$.fromPowerAction(PowerManagement.scala:56) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
2016-08-16 15:41:00.118506500  	at collins.controllers.actions.resources.IntakeStage1Action.identifyAsset(IntakeStage1Action.scala:63) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
2016-08-16 15:41:00.118508500  	at collins.controllers.actions.resources.IntakeStage1Action.execute(IntakeStage1Action.scala:54) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
2016-08-16 15:41:00.118511500  	at collins.controllers.actions.SecureAction$$anonfun$handleExecution$1.apply(SecureAction.scala:173) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
2016-08-16 15:41:00.118513500  	at collins.controllers.actions.SecureAction$$anonfun$handleExecution$1.apply(SecureAction.scala:173) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
2016-08-16 15:41:00.119889500  [warn] application - Unhandled exception
2016-08-16 15:41:00.119906500  play.api.Application$$anon$1: Execution exception[[IllegalStateException: No IPMI configuration for asset MY_ASSET]]
2016-08-16 15:41:00.119909500  	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
2016-08-16 15:41:00.119911500  	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
2016-08-16 15:41:00.119913500  	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
2016-08-16 15:41:00.119916500  	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
2016-08-16 15:41:00.119919500  	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.7.jar:na]
2016-08-16 15:41:00.119921500  Caused by: java.lang.IllegalStateException: No IPMI configuration for asset MY_ASSET
2016-08-16 15:41:00.119923500  	at collins.power.management.IpmiPowerCommand$.fromPowerAction(PowerManagement.scala:56) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
2016-08-16 15:41:00.119925500  	at collins.controllers.actions.resources.IntakeStage1Action.identifyAsset(IntakeStage1Action.scala:63) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
2016-08-16 15:41:00.119928500  	at collins.controllers.actions.resources.IntakeStage1Action.execute(IntakeStage1Action.scala:54) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
2016-08-16 15:41:00.119930500  	at collins.controllers.actions.SecureAction$$anonfun$handleExecution$1.apply(SecureAction.scala:173) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
2016-08-16 15:41:00.119932500  	at collins.controllers.actions.SecureAction$$anonfun$handleExecution$1.apply(SecureAction.scala:173) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
```

I've created this system the same way I created all our other systems except the lshw data is 'handcrafted'. I can provide that but it seems unrelated. Then again, I don't know what else would case this state.

**Comment by byxorna** [comment]
What status is your asset in? New?

I believe collins tries to IPMI poke machines in New when accessing them directly via resource ID, as part of the new->unallocated induction workflow. Try searching for New assets and click your machine in the list, and let me know if that works?

FYI, the same happens when an asset is inducted but is inaccessible over IPMI (wrong ipmi configuration, networking issues, etc), and collins redirects you to a help page if you try to go straight to the resource id.

**Comment by discordianfish** [comment]
@byxorna Hrm so it didn't look like it tried to IPMI-poke the machines. Remember I specified `generate_ipmi=false`, so there was no IPMI configuration available. In the meanwhile I added a fake ipmi config and now can access the asset. Is it intended that I can't see 'new' assets without ipmi configuration? That seems reasonable to me, but:

a) It should not throw a 500. Personally I would just show it and disable stuff that might rely on IPMI config?
b) I need 'servers' without ipmi[1] and adding 'fake' ipmi config is a ugly workaround. Can I configure collins to not require ipmi config? Or should I create a new asset type?


1) http://photos.imgix.com/racking-mac-pros :)

**Comment by discordianfish** [comment]
@byxorna Just ran into this again when trying to use the web intake workflow. Looks like this only works for systems that have ipmi data..?

**Comment by byxorna** [comment]
@discordianfish yep, that is definitely plausible. It was never really built to support web intake for machines without IPMI, because half of the physical induction workflow is dependent on confirming the IPMI details work and poke the right server. For machines without IPMI, I have always done induction via API :/

**Comment by Primer42** [comment]
To be honest, I think the whole intake flow needs to be revisited.  It was built to conform to Tumblr's initial intake policy, and is far too opinionated.

**Comment by byxorna** [comment]
@Primer42 not just Tumblr, we use it too. Generally though, it is definitely tailored towards rackmounted IPMI capable machines running a homogenous linux-y OS :P

**Comment by discordianfish** [comment]
Yes, this all makes sense for our linux systems as well. For our osx systems it don't. But they still have a rack position and especially the power config which I would like to keep.

So basically with intake screen without the ipmi stuff would do. Otherwise I have to reimplement this in some 3rd party intake web app. Will look into how much it would take to make Collins support assets without ipmi but probably have to go with later option.

**Comment by byxorna** [comment]
Theres been some discussion about how to support a modular physical intake system. I think perhaps a separate codepath for assets without IPMI configuration could skip UID verification and just have you verify chassis asset tag, and input power config. Sounds easy enough?

**Comment by discordianfish** [comment]
@byxorna Yes, that would be perfect.

**Comment by discordianfish** [comment]
@byxorna So I looked into this today. It would be easy to just skip the first UID step if ipmi config is missing. It though this should do the job but somehow it doesn't:

```
diff --git a/app/collins/controllers/actions/resources/FindAction.scala b/app/collins/controllers/actions/resources/FindA
ction.scala
index 31c8404..e3413f9 100644
--- a/app/collins/controllers/actions/resources/FindAction.scala
+++ b/app/collins/controllers/actions/resources/FindAction.scala
@@ -7,6 +7,8 @@ import collins.controllers.actions.ActionHelper
 import collins.controllers.actions.RequestDataHolder
 import collins.controllers.actions.asset.AssetFinderDataHolder
 import collins.controllers.actions.asset.{ FindAction => AssetFindAction }
+import collins.models.IpmiInfo
+import collins.models.Asset
 import collins.models.asset.AssetView
 import collins.models.shared.Page
 import collins.models.shared.PageParams
@@ -38,7 +40,12 @@ case class FindAction(
         val rmap = requestMap.filterNot(kv => ignores.contains(kv._1))
         // If the only thing specified was the tag, and intake is allowed, go through intake
         if (rmap.contains("tag") && rmap.size == 1 && assetIntakeAllowed(asset).isEmpty)
-          Redirect(collins.app.routes.Resources.intake(asset.id, 1))
+          IpmiInfo.findByAsset(asset.asInstanceOf[Asset]) match {
+            case Some(ipmi) =>
+              Redirect(collins.app.routes.Resources.intake(asset.id, 1))
+            case None =>
+              Redirect(collins.app.routes.Resources.intake(asset.id, 2))
+          }
         else
           Status.Redirect(asset.remoteHost.getOrElse("") + collins.app.routes.CookieApi.getAsset(p.items(0).tag))
       case n =>
```

It still sends me to the UID verification. I probably don't understand how to properly cast the AssetView to an Asset. Will learn me some scala next week. Guess some basics should help :).

**Comment by discordianfish** [comment]
Doh', actually it worked - the problem was just that I forgot collins generates ipmi by default.

**Comment by discordianfish** [comment]
@byxorna I've submitted this as #492 

But it also made me think about this in general and what further customizations I need and I was thinking maybe it would make sense to remove the intake stuff from collins altogether and have people write their own intake process. Writing a intake web service which talks to collins should be straight forward and it's a easy way to decouple the intake from collins.

**Comment by byxorna** [comment]
@discordianfish i think a batteries included but removable approach would be best. Making intake optional if you have specific needs (and ability to customize), but out of the box it works as advertised.

**Comment by discordianfish** [comment]
@byxorna Fair enough, but if the intake process should stay it would make sense to clean stuff up a bit. I don't really understand the need for the 'hack' at hand in the first place.

I assume it's because you want to be able to get from the collins front page to the intake process just by scanning the tag. For this every request to /find gets redirected to the intake on these conditions: https://github.com/tumblr/collins/blob/master/app/collins/controllers/actions/resources/FindAction.scala#L39

What about having a checkbox instead that says 'redirect new to intake' which is checked by default (or could be remembered in session/local storage etc) which would always redirect find results with a single 'new' asset to intake? That would make the conditions a bit less 'magic' and allow me to use another field than the asset tag to trigger the intake.

Still, I'd also need to disable the chassis tag verification since we don't store that currently either (and our scale doesn't deem that level of consistency checks necessary).

If you think this makes sense, I'll look into it.

**Comment by byxorna** [comment]
Yea, I think the magic "search for asset and get intake flow" is pretty confusing unless you have already been indoctrinated. Perhaps moving the intake triggering from the search page to a banner on the asset's page if eligible for induction?

That way the flow is:

* scan asset tag on search page
* get taken to asset page (in New status)
* click banner that says "Perform Physical Induction on 001234"

Its an additional step, but definitely much clearer.

**Comment by discordianfish** [comment]
@byxorna I would assume this additional step is a problem for tumblr. And while it wouldn't be for us, I'd like to avoid it too.
What do you dislike about my proposed checkbox? We don't even need to make it default. If we store it in the session/localStorage/cookie, the DC technician can just click the box and it will stay checked for any number of systems they want to intake.

**Comment by byxorna** [comment]
This seems like a reasonable option, as long as there is sufficient pop-over help text explaining what the checkbox does
