### ISSUE TITLE
Collins 2.0 does not start

### ISSUE THREAD

**Issue by t1mota** [tumblr/collins#558]
Hi ALL, 
recently tried to run collins on java 1.8 with JCE - it did failed to start with error

2017-06-21 23:59:41,958 - [ERROR] - from application in main Failed to create assetlog
play.api.PlayException: [neither features.syslogAsset or multicollins.thisInstance were specified]
        at collins.util.Tattler$$anonfun$syslogAsset$2.apply(Tattler.scala:84) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
        at collins.util.Tattler$$anonfun$syslogAsset$2.apply(Tattler.scala:84) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
        at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-library-2.11.7.jar:na]
        at collins.util.Tattler.syslogAsset$lzycompute(Tattler.scala:83) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
        at collins.util.Tattler.syslogAsset(Tattler.scala:83) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
        at collins.util.Tattler.system(Tattler.scala:75) ~[collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
        at collins.util.config.Configurable$class.mergeReferenceAndSave(Configurable.scala:117) [collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
        at collins.solr.SolrConfig$.mergeReferenceAndSave(SolrConfig.scala:12) [collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
        at collins.util.config.Configurable$class.initialize(Configurable.scala:49) [collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
        at collins.solr.SolrConfig$.initialize(SolrConfig.scala:12) [collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
        at collins.util.config.Registry$$anonfun$validate$1.apply(Registry.scala:56) [collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
        at collins.util.config.Registry$$anonfun$validate$1.apply(Registry.scala:54) [collins.collins-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) [org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) [org.scala-lang.scala-library-2.11.7.jar:na]

javac -version
javac 1.8.0_131

Can you help with this issue please

**Comment by michaeljs1990** [comment]
I have seen this error before "neither features.syslogAsset or multicollins.thisInstance were specified" first I would check that one of those is set... but more generally this can sometimes just be do to anything in your config being bad and not being read properly.

**Comment by byxorna** [comment]
@t1mota yea, this (unfortunately) is odd error handling from config file parsing most likely. Can you post your config[s]?
