### ISSUE TITLE
Collins will not start due to Akka Errors

### ISSUE THREAD

**Issue by blurtonator** [tumblr/collins#586]
Hello,
Trying to get Collins up and running and it will not start due to issues with Akka. Collins version 2.2 on CentOS 7 with JDK 1.7.

**The error I get while starting is:**
```
akka.ConfigurationException: configuration problem while creating [akka://application/user/change_queue_processor] with router dispatcher [akka.actor.default-dispatcher] and mailbox [akka.actor.default-mailbox] and routee dispatcher [akka.actor.default-dispatcher] and mailbox [akka.actor.default-mailbox]
        at akka.actor.LocalActorRefProvider.actorOf(ActorRefProvider.scala:752)
        at akka.actor.dungeon.Children$class.makeChild(Children.scala:207)
        at akka.actor.dungeon.Children$class.attachChild(Children.scala:42)
        at akka.actor.ActorCell.attachChild(ActorCell.scala:369)
        at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:552)
        at collins.callbacks.Callback$.setupCallbacks(Callback.scala:21)
        at Global$.onStart(Global.scala:45)
        at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:146)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: akka.ConfigurationException: Configuration missing for router [akka://application/user/change_queue_processor] in 'akka.actor.deployment' section.
        at akka.routing.FromConfig.verifyConfig(RouterConfig.scala:297)
        at akka.routing.RoutedActorRef.<init>(RoutedActorRef.scala:40)
        at akka.actor.LocalActorRefProvider.actorOf(ActorRefProvider.scala:750)
        ... 22 more
```

Configuration is very minimally different than the stock production.conf (just changed the mysql details to point to our cluster instead of a local instance).

**Comment by lexx-bright** [comment]
Any suggestions on how to fix/workaround this error?
